nondex-core/src/test/java/edu/illinois/nondex/core/AbstractCollectionTest.java
nondex-core/src/test/java/edu/illinois/nondex/core/ConcurrentHashMapTest.java
nondex-core/src/test/java/edu/illinois/nondex/core/HashMapTest.java
nondex-core/src/test/java/edu/illinois/nondex/core/HashSetTest.java

I noticed that there seem to be some misspellings in the test names in these test classes along with the same misspelling in the helper method, and so this pull request simply addresses those misspellings.

Fixing misspelling of parametrized -> parameterized

---

nondex-common/src/main/java/edu/illinois/nondex/common/Configuration.java
nondex-common/src/main/java/edu/illinois/nondex/common/ConfigurationDefaults.java
nondex-common/src/main/java/edu/illinois/nondex/shuffling/ControlNondeterminism.java

This pull request changes the logic to output the stack trace when a single choice point is found to be the issue into a new debug file. Note that writing to file invokes Nondex, so special care is in place to make sure to prevent infinite calls to file writing, but may schew the SHUFFLE and COUNT values, but may not be an issue.

Writing stack trace to debug file

---

nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/Instrumenter.java

This actually happened when running on an old jar without the .md5 files in it. It could happen also when a jar does not have all the class files in it.

fixed NPE when some file is not in the jar

---

nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/Instrumenter.java
nondex-maven-plugin/src/it/clean-it/invoker.properties
nondex-maven-plugin/src/it/clean-it/pom.xml
nondex-maven-plugin/src/it/clean-it/src/test/java/edu/illinois/nondex/it/AppTest.java
nondex-maven-plugin/src/it/clean-it/verify.groovy
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/CleanMojo.java

After this is merged, users will be able to clean NonDex artifacts by invoking `mvn nondex:clean`.
@august782, @alexgyori please review.

added a new Mojo to clean artifacts

---

nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/DebugMojo.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/DebugTask.java

This pull request changes the reporting of DebugTask to also report the name of the test to be debugged along with the path to the corresponding debug file.
Note that this requires a change to failsWithConfig to return the actual failing configuration instead of booleans (where null represents no failure) and changes to all callers of failsWithConfig accordingly. Before, a new failing configuration was made wrapped around some existing failing configuration instead of the debugged one, but now to get the path to the debug file the failing configuration from the last debugging is required.

Update Debug Task

---

nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/DebugMojo.java

Like previous fix with getting right paths to .nondex in the NonDexMojo, this one does the same for the DebugMojo in case of multi-module.

Fixed paths to use correct baseDir when looking for files in .nondex

---

nondex-common/src/main/java/edu/illinois/nondex/shuffling/ControlNondeterminism.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/DebugMojo.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/DebugTask.java

This pull request makes sure debugging goes over the seeds in a List order for consistency.
It also adds logic in shuffling to not shuffle when there is at most one element in the collection, as to help with debugging and not searching as large a range.

Fixing debug order and small optimization to debugging

---

nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/DebugTask.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/NonDexSurefireExecution.java

This pull request allows debugging to run higher levels of granularity instead of always the set test, as it requires the configuration in the surefire to be updated to use the different test class or empty (for project).
Also adds test class as possible level.

Global debugging

---

nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/CleanSurefireExecution.java

Surefire for some reason counts skipped as failure, which we don't want, so this simply checks that.

Fixed to add check if failure is skipped

---

nondex-common/src/main/java/edu/illinois/nondex/common/Configuration.java
nondex-instrumentation/pom.xml
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/NonDexSurefireExecution.java
nondex-test/pom.xml

NonDex did not work if the path to your current project had any space in it. This should fix that.

escaping paths to account for space

---

nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/WeakHashMapShufflingAdder.java

As discussed before, the new init method should be appended instead of added.
This PR fixed this bug in weakHashMapShufflingAdder.

Fix <init> method in WeakHashMap

---

checkstyle.xml

Checkstyle should check for all kinds of print, not just println

Modified checkstyle to check for system print

---

nondex-core/src/main/java/java/util/concurrent/PriorityBlockingQueue.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/CVFactory.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/ClassVisitorShufflingAdder.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/Instrumenter.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/PriorityBlockingQueueShufflingAdder.java
nondex-test/src/test/java/edu/illinois/nondex/core/QueueTest.java

The toString method is not shuffled by NonDex before.
Since the PriorityBlockingQueue toString method didn’t use the iterator
of PriorityBlockingQueue, this method needs to be instrumented.
PriorityBlockingQueue is originally classified as a standard class to
instrument because only toArray method is instrumented. I moved the
class to special class to instrument and instrumented both toString and
toArray methods.

Fix toString bug in PriorityBlockingQueue

---

nondex-common/src/main/java/edu/illinois/nondex/shuffling/ControlNondeterminism.java

@alexgyori 
Since we are overriding a method with no "throws" signature and IOException is not a runtime exception, so I choose to throw a RunTimeException.
And I am kind of confused why there are two catch blocks in the original code. Code in the try block will only throw IOException, I don't see any chance that it will catch any other exceptions.

Modify JVMShutdownHook to throw RuntimeException when IOException occurs

---

.travis.yml

Currently, NonDex does not build properly on Travis due to changes in default distributions. This pull request aims to explicitly set the distribution for the Travis build. Also, the new distribution does not allow for some functionality we were relying on before, such as jdk_switcher, so we have to change back to setting using the jdk key. Unfortunately, this breaks the OSX build, and there seems to be no easy way of setting different JDK version as to not crash for different OS. For now, this pull request just puts OSX builds into allow_failures.

Fixing Travis build

---

nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/AbstractNonDexMojo.java

This fixes issue #81 as https://github.com/TestingResearchIllinois/NonDex/blob/a1d2fa21e19acd5453abf4c549b61101ac115e3b/nondex-common/src/main/java/edu/illinois/nondex/common/Mode.java#L32 indicates, there are only two modes: ONE and FULL. This PR removes the incorrect part.
Please note in order for the change to show up, you need to use the snapshot version when using the plugin.

Fix the out-of-date help text for mode of debug in the maven plugin

---

checkstyle.xml
nondex-annotations/pom.xml
nondex-common/pom.xml
nondex-instrumentation/pom.xml
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/ConcurrentHashMapShufflingAdder.java
nondex-instrumentation/src/test/java/edu/illinois/nondex/instr/InstrumenterTest.java
nondex-maven-plugin/pom.xml
nondex-test/pom.xml

Updating the checkstyle version to 8.18 due to security vulnerabilities. Additionally, updating the configuration files to match the new updated version and reformatting some source files that now fail some checkstyle checks.

Updating checkstyle due to security vulnerabilities

---

nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/CleanSurefireExecution.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/DebugTask.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/NonDexSurefireExecution.java

In Issue #123, debug mode throws an NPE when debugging multiple tests because, upon reaching to debug the second test, the configuration is still stuck with using the execution ID from debugging the prior test.
The reason is that in between runs of NonDex the updated Surefire configuration (which passes in the relevant configuration options as arguments for running) is not reset, and it maintains some configuration options from before. The later runs, when parsing the arguments, always parses the old ones. This pull request resets the Surefire configuration between runs.
The other change, to NonDexSurefireExecution.java, is a by-product of doing the resetting, because integration tests now fail due to having configuration nodes without a <test> child. The change there simply adds one if …

Resetting the Surefire configuration between runs

---

checkstyle.xml
nondex-annotations/pom.xml
nondex-common/pom.xml
nondex-common/src/main/java/edu/illinois/nondex/common/Utils.java
nondex-instrumentation/pom.xml
nondex-maven-plugin/pom.xml
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/DebugMojo.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/NonDexSurefireExecution.java
nondex-test/pom.xml

This pull request updates the checkstyle version for security purposes, as suggested by GitHub's dependabot. This pull request also updates checkstyle configuration files because the new version breaks backwards compatibility, and also updates formatting in some files to match the configurations as well.

Updating checkstyle version for security purposes

---

nondex-common/src/main/java/edu/illinois/nondex/shuffling/ControlNondeterminism.java

This pull request removes the `lengths` list field, because it is not actually used elsewhere in the code and also can cause potential concurrency problems when NonDex is run in some projects.

Removing lengths list due to potential concurrency problems

---

nondex-common/src/main/java/edu/illinois/nondex/common/Configuration.java
nondex-common/src/main/java/edu/illinois/nondex/common/Level.java
nondex-common/src/main/java/edu/illinois/nondex/common/NonDex.java
nondex-common/src/main/java/edu/illinois/nondex/common/Utils.java
nondex-common/src/main/java/edu/illinois/nondex/shuffling/ControlNondeterminism.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/CVFactory.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/Instrumenter.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/AbstractNonDexMojo.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/CleanSurefireExecution.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/DebugMojo.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/DebugTask.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/NonDexMojo.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/NonDexSurefireExecution.java

In Java 9+, due to the introduction of the [module system](https://openjdk.java.net/jeps/261), the original logger `java.util.logging` has been separated into an isolated module called `java.logging`. Our experiment indicates that `java.base` can not access any other module or jar during the initialization of boot layer even if we used `—add-reads` option.
We think the usage of class `Level` is minimal so we propose to reimplement the simplified version for the custom `Logger` instead of calling `java.util.logging.Level`.
P.S. Another solution can be using [`java.lang.System.Logger`](https://docs.oracle.com/javase/9/docs/api/java/lang/System.Logger.html) which is designed to log bootstrap information in Java9+.

Rewrite custom Level class in place of java.util.logging.Level

---

nondex-instrumentation/pom.xml
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/ClassVisitorShufflingAdder.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/ConcurrentHashMapShufflingAdder.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/HashMapShufflingAdder.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/IdentityHashMapShufflingAdder.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/MethodShufflingAdder.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/PriorityBlockingQueueShufflingAdder.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/PriorityQueueShufflingAdder.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/WeakHashMapShufflingAdder.java
nondex-maven-plugin/pom.xml

Updated asm version to 9.0 because `ASM5` doesn't support Java9 and other later versions. Also updated the versions of `maven-shade-plugin` and `maven-plugin-plugin` to match the change.

Bump asm.version from 5.1 to 9.0

---

nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/DebugMojo.java

Using entrySet instead of keySet, we do not have to access hashmap again to obtain the value. This could be a potential performance improvement for many values that share one hash value.
- The fixing report is generated by Amazon CodeGuru reviewer
- Test cases in nondex-maven-plugin module passed

performance improvement on hashmap

---

.gitignore
nondex-common/pom.xml
nondex-common/src/main/java/edu/illinois/nondex/common/Utils.java
nondex-common/src/main/java/edu/illinois/nondex/shuffling/ControlNondeterminism.java
nondex-core/pom.xml
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/CVFactory.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/Instrumenter.java
nondex-instrumentation/src/main/java/edu/illinois/nondex/instr/Main.java
nondex-instrumentation/src/test/java/edu/illinois/nondex/instr/InstrumenterTest.java
nondex-maven-plugin/src/it/clean-it with-whitespace-in-path/pom.xml
nondex-maven-plugin/src/it/clean-it/pom.xml
nondex-maven-plugin/src/it/comprehensive/pom.xml
nondex-maven-plugin/src/it/excluded-groups-it/module1/pom.xml
nondex-maven-plugin/src/it/excluded-groups-it/pom.xml
nondex-maven-plugin/src/it/failing-it/pom.xml
nondex-maven-plugin/src/it/inexistent-variable-argline-it/pom.xml
nondex-maven-plugin/src/it/simple-it/pom.xml
nondex-maven-plugin/src/it/simple-multimodule-it/pom.xml
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/AbstractNonDexMojo.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/NonDexSurefireExecution.java
nondex-test/pom.xml
pom.xml

In recent tests with Java 9/10/11/17 with all code changes in https://github.com/TestingResearchIllinois/NonDex/pull/155, no problems are found. This PR addresses the changes in https://github.com/TestingResearchIllinois/NonDex/pull/155, and makes minor changes to resolve its conflicts with the current main branch.
After this PR NonDex Maven plugin (1.1.3-SNAPSHOT) shall work with both Java 8 and Java 9+.

Add support for Java 9+: Addressed code changes in #155 and resolved conflicts.

---

README.md
nondex-common/src/main/java/edu/illinois/nondex/common/ConfigurationDefaults.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/AbstractNonDexMojo.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/NonDexMojo.java

Currently, NonDex executes one single clean run before shuffled runs. Then, it reports a test as flaky if it passes in the clean run and fails in one of the shuffled runs. However, in practice there are many ND (e.g. a test with timeout assertion that fails occasionally) / NIO tests (e.g. a test that silently changes some external states such that it fails in the second consecutive `mvn -test` run) falsely reported as ID in this way. 
This PR allows users to manually set the number of clean NonDex runs in command line. NonDex will print out a summary of the clean runs (e.g. "SomeTest" fails in 1/7 clean runs), and exclude all tests that fail in clean runs from the final report "Across all seeds: xxx". Users can use this feature to verify whether a flaky test is really ID.
Sample output on …

Allowing customizing number of clean NonDex runs in command line

---

nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/DebugTask.java
nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/NonDexMojo.java

This PR addresses the idea in (https://github.com/TestingResearchIllinois/NonDex/pull/53) to report many invocations from all seeds that can reproduce error. 
3 changes are made w.r.t the original PR: 
- Resolve code conflict with the latest master branch
- If a test is ND (falsely identified as ID by NonDex, which is quite common), `reportDebugInfo()` , which subsequently calls `failsWithConfig()` can return `null` even if being run with the same "originally failing" configuration. Then, the list `allFailingConfigurations` can contain `null` entries, which causes NPE when iterating through the list. The solution is to add a null check to avoid NPE thrown by `makeResultString()`.
- The original PR did not add the results found by linear search to the output list. This PR corrects it.

Allow debug to report multiple invocations

---

nondex-test/pom.xml
pom.xml

This PR addressed the code changes for sanity w.r.t. Maven Central Deployment. It is also the last PR for NonDex 2.1. It does the followings:
1. Version 1.6.7 of `nexus-staging-maven-plugin` is deprecated and causes failures in deploying. Bump the version to 1.6.13.
2. If we use the `mvn deploy -P` scheme (rather than `mvn release:prepare` and `mvn release:perform`), we need to also configure `org.sonatype.plugins` (rather than just `maven-deploy-plugin`) to skip deployment, or that the integration test module will still be deployed.
3. Sonatype enables a scheme to ensure a source code `.jar` file and a Javadoc `.jar` file presented in all submodules. However, as our test module has no `src/main` folder, such jars are not generated, and sanity check fails. The Sonatype maintainers suggest …

Ensure Sanity for Sonatype checks

---

nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/NonDexMojo.java

**Description**
Every  `NonDexSurefireExecution` has an `executionId` and a `runFilePath`. The `runFilePath` is configured based on the `executionId` [link](https://github.com/TestingResearchIllinois/NonDex/blob/master/nondex-common/src/main/java/edu/illinois/nondex/common/Configuration.java#L213). The `NonDexMojo` class consists of a `List<NonDexSurefireExecution>` called `executions`. Within the `execute` method, this list is populated.
For each `execution` in this list , the `executionId` of the corresponding execution is being appended to a file whose path is the `runFilePath` of the first member of this list. This base path information is not stored anywhere and fetched from the first element for writing each `executionId`. This is the portion of the code being refactored as part of …

Refactored code to write run id to execution file

---

nondex-instrumentation/pom.xml
nondex-maven-plugin/pom.xml
nondex-test/pom.xml
pom.xml

Version bumps to add support for Java 17.
Now build with Java 17 succeeded and NonDex ran fine with 2 sample projects.
More extensive test will be appreciated.

Support java 17

---

nondex-maven-plugin/src/main/java/edu/illinois/nondex/plugin/CleanSurefireExecution.java

2 Changes:
- Do a merge when multiple `--patch-modules java.base` in argline
- Remove placeholders in final argline

Fix JVM crashing issues
